#!/usr/bin/env bash
# configure web server for error 404 and add custom he
sudo apt-get update
sudo apt-get install nginx -y
sudo sed -i "http {/a \ add_header X-Served-By $hostname;" /etc/nginx/nginx.conf
sudo service nginx restart
