#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend budabos.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 168448-web-01 54.84.65.229:80
        server 168448-web-02 54.175.134.97:80
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
